apiVersion: v1
kind: Namespace
metadata:
  name: tasks-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
  namespace: tasks-system

spec:
  selector:
    matchLabels:
      app: tasks

  template:
    metadata:
      labels:
        app: tasks

    spec:
      terminationGracePeriodSeconds: 60

      initContainers:
        - name: init-migrate
          image: task-image
          command: ["./admin"]

      containers:
        - name: tasks-api
          image: task-image

          ports:
            - name: tasks-api
              containerPort: 3000
            - name: tasks-api-debug
              containerPort: 4000

          readinessProbe: # readiness probes mark the service available to accept traffic.
            httpGet:
              path: /debug/readiness
              port: 4000
            initialDelaySeconds: 2
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2

          livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
            httpGet:
              path: /debug/liveness
              port: 4000
            initialDelaySeconds: 2
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu

            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

---
apiVersion: v1
kind: Service
metadata:
  name: tasks-api
  namespace: tasks-system
